name: labook
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.1.0

  #ui
  animated_bottom_navigation_bar: ^1.0.0
  flutter_screenutil: ^5.4.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  google_fonts: ^3.0.1

  # backend
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  pdf: ^3.8.1
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true